#!/usr/bin/env bash

# docker-images
export DOCKER_HOST_IP=172.17.0.1 # makes shell startup faster and avoid printing error when docker is not running
export SKIP_DOCKER_CHECK=true # speeds up startup a bit

# make catalina shut up about zsh
export BASH_SILENCE_DEPRECATION_WARNING=1

# make docker shut up about scanning
export DOCKER_SCAN_SUGGEST=false

source ~/.bashrc

# fixes weird PG connection issue
export PGHOST=localhost

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

