#!/usr/bin/env bash

[ -z "$PS1" ] && return # do nothing for non-interactive sessions to avoid bugs from sending to stderr/stdout

eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_NO_ENV_HINTS=1

source ~/dotfiles/bash/env.sh
source ~/dotfiles/bash/alias.sh
source ~/dotfiles/bash/prompt.sh
source ~/dotfiles/bash/bundler-exec.sh
source ~/dotfiles/bash/copy_on_ssh.sh
source ~/dotfiles/bash/personal.sh

source /opt/homebrew/etc/bash_completion # for kubectl, needs `brew install bash-completion`
for file in ~/dotfiles/autocomplete/* ; do
  source "$file"
done

# Mise: multi language version switcher
eval "$(/opt/homebrew/bin/mise activate bash)"

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Gcloud
source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"
file=/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc
[ -f $file ] && source $file
file=/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc
[ -f $file ] && source $file

# secret
file=~/dotfiles/secret/bash.sh
[ -f $file ] && source $file

# TODO: fix chruby https://github.com/ddworken/hishtory/issues/44
# Hishtory Config:
# install via https://github.com/ddworken/hishtory
#export PATH="$PATH:/Users/mgrosser/.hishtory"
#source /Users/mgrosser/.hishtory/config.sh
#hishtory config-set displayed-columns Command 'Exit Code' CWD Runtime # Timestamp Hostname
#hishtory config-set timestamp-format '2006-01-02 15:04:39'
